apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs
  labels:
    app: songs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs
  template:
    metadata:
      labels:
        app: songs
    spec:
      containers:
        - name: songs
          image: marinastancu/songs:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: songsdb
                  key: URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: songsdb
                  key: USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: songsdb
                  key: PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: PASSWORD
            - name: RABBITMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: QUEUE
---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
spec:
  selector:
    app: songs
  ports:
    - protocol: TCP
      port: 8080